name: jax-gamma-ray-prototype-gpu

channels:
  - conda-forge

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  # core dependencies
  - python=3.11
  - gammapy=1.2
  - ipykernel
  - pandas
  - pip:
    - jax[cuda12]==0.4.29
    - jaxlib==0.4.29
